import { z } from "zod"

export const productSchema = z.object({
    name: z.string().min(1, "Name is required"),
    sku: z.string().min(1, "SKU is required"),
    barcode: z.string().optional(),
    description: z.string().optional(),
    short_description: z.string().optional(),
    price: z.number().min(0, "Price must be greater than or equal to 0"),
    cost_price: z.number().min(0, "Cost price must be greater than or equal to 0"),
    wholesale_price: z.number().min(0, "Wholesale price must be greater than or equal to 0"),
    category: z.string().min(1, "Category is required"),
    sub_category: z.string().optional(),
    brand: z.string().optional(),
    manufacturer: z.string().optional(),
    volume: z.number().min(0, "Volume must be greater than or equal to 0"),
    weight: z.number().min(0, "Weight must be greater than or equal to 0"),
    dimensions: z.string().optional(),
    min_stock_level: z.number().min(0, "Minimum stock level must be greater than or equal to 0"),
    max_stock_level: z.number().min(0, "Maximum stock level must be greater than or equal to 0"),
    quantity: z.number().min(0, "Quantity must be greater than or equal to 0"),
    discount: z.number().min(0, "Discount must be greater than or equal to 0").max(100, "Discount cannot exceed 100%"),
    tax_rate: z.string().optional(),
    shipping_class: z.string().optional(),
    skin_type: z.string().optional(),
    benefits: z.string().optional(),
    ingredients: z.string().optional(),
    expiry_date: z.string().optional(),
    manufacturing_date: z.string().optional(),
    warranty: z.string().optional(),
    badge: z.string().optional(),
    meta_title: z.string().optional(),
    meta_description: z.string().optional(),
    meta_keywords: z.string().optional(),
    tags: z.string().optional(),
    files: z.array(z.string()),
})

export type ProductFormValues = z.infer<typeof productSchema>
